//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KitchensWithZest.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MessageBox
    {

        public int MessageId { get; set; }

        [Required(ErrorMessage = "Please enter your first name")]
        [RegularExpression(@"^[A-Za-z]*$", ErrorMessage = "First name format is not valid")]
        public string FirstName { get; set; }


        [Required(ErrorMessage = "Please enter your last name")]
        [RegularExpression(@"^[A-Za-z]*$", ErrorMessage = "Last name format is not valid")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Please enter your phone number")]
        [Phone(ErrorMessage = "Phone number is invalid")]
        public string Phone { get; set; }

        [Required(ErrorMessage = "Please enter your email")]
        [RegularExpression(@"^[A-Za-z0-9]+@[A-Za-z0-9]+(\.)+[A-Za-z0-9]{2,10}$", ErrorMessage = "Email is not valid")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Please enter a subject title")]
        public string Subject { get; set; }

        [Required(ErrorMessage = "Please enter your message")]
        public string Content { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd HH:mm}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> SubmissionTime { get; set; }
    }
}
