////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated from a template.
////
////     Manual changes to this file may cause unexpected behavior in your application.
////     Manual changes to this file will be overwritten if the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//namespace KitchensWithZest.Models
//{
//    using System;
//    using System.Collections.Generic;
//    using System.ComponentModel;
//    using System.ComponentModel.DataAnnotations;
//    using System.ComponentModel.DataAnnotations.Schema;
//    using System.Web;

//    public partial class Gallery
//    {
//        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
//        public Gallery()
//        {
//            this.Photos = new HashSet<Photo>();
//        }

//        public int GalleryId { get; set; }
//        [Required]
//        public string Title { get; set; }
//        [Required]
//        public string Description { get; set; }
//        [DisplayName("Main Photo")]
//        public string MainPhotoPath { get; set; }
//        [NotMapped]
//        public HttpPostedFileBase MainPhotoFile { get; set; }
//        [DisplayName("Gallery Images")]
//        public string ImagesPath { get; set; }
//        [NotMapped]
//        public IEnumerable<HttpPostedFileBase> ImagesFiles { get; set; }

//        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
//        public virtual ICollection<Photo> Photos { get; set; }
//    }
//}
